# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZIjtIRJo7LMCFMx5UVjDCYrfd-FJbPB8
"""

#pip install streamlit torch torchvision

import streamlit as st
from PIL import Image
import torch

# Assuming predict_uploaded_image modified to accept file-like object instead of uploading itself:
def predict_image(model, transform, class_names, device, img):
    image = Image.open(img).convert("RGB")
    input_tensor = transform(image).unsqueeze(0).to(device)

    model.eval()
    with torch.no_grad():
        output = model(input_tensor)
        pred_class_idx = output.argmax(dim=1).item()

    return class_names[pred_class_idx], image

st.title("Land Cover Classifier")

uploaded_file = st.file_uploader("Upload a satellite image", type=["jpg", "png"])

if uploaded_file:
    label, image = predict_image(my_model, random_trans224, DATA_LABELS, device, uploaded_file)
    st.image(image, caption=f"Predicted: {label}")

